### ISSUE TITLE
interactive fitter breaks occassionaly with TypeError

### ISSUE THREAD

**Issue by GiantMolecularCloud** [jdhenshaw/scousepy#34]
Bug report:
Occassionally the interactive fitter in stage_2 breaks, displays a lengthy traceback and brings up a command prompt. After that the fitter window seems to continue to work but does not advances to the next spectrum. Instead "'enter' key acknowledged.  Moving to next spectrum or next step..." is printed as often as "enter" is pressed. The fitting itself continues to work, i.e. the keys 1,2,3,f still work.

~~I have the feeling that this error occurs when pressing a key while scouse is calculating something in the background but I cannot actively reproduce it.~~
Edit: Now it happened when I definitely did not press any key. 
Edit2: And it happened again on exactly the same spectrum as the first time.

The traceback that's printed to the terminal:
```
=============================================================
If you are happy with this fit, press Enter.  Otherwise, use the 'f' key to re-enter the interactive fitter.
'enter' key acknowledged.  Moving to next spectrum or next step...
Fitting 42 out of 54
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-31834ddaffa6> in <module>
      1 s = scouse.stage_2(s,
      2                    verbose     = True,
----> 3                    write_ascii = True
      4                   )

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/scouse.py in stage_2(self, verbose, write_ascii, autosave, bitesize, nspec, training_set)
    461                     bf = fitting(self, SAA, saa_dict, SAAid,
    462                                  training_set=self.training_set,
--> 463                                  init_guess=firstfit)
    464                 SAAid = SAA.index
    465                 firstfit=False

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/stage_2.py in fitting(self, scouseobject, SAA, saa_dict, count, training_set, init_guess, guesses)
    275                                             count, guesses=guesses,
    276                                             training_set=True,
--> 277                                             init_guess=init_guess)
    278
    279         return bf

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/stage_2.py in fitting(self, scouseobject, SAA, saa_dict, count, training_set, init_guess, guesses)
    244             self.spec = spec
    245             self.trainingset_fit(spec, init_guess=init_guess,
--> 246                                        guesses=guesses)
    247
    248             with warnings.catch_warnings():

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/stage_2.py in trainingset_fit(self, spec, init_guess, guesses)
    187                          guesses=guesses,
    188                          fittype=scouseobject.fittype,
--> 189                          use_lmfit=True)
    190             spec.specfit.plot_fit(show_components=True)
    191             spec.specfit.plotresiduals(axis=spec.plotter.axis,

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/config.py in decorator(self, *args, **kwargs)
    143             new_kwargs[arg] = kwargs[arg]
    144
--> 145         f(self, *args, **new_kwargs)
    146
    147     # documentation should be passed on, else sphinx doesn't work and the user can't access the docs

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in __call__(self, interactive, usemoments, fittype, clear_all_connections, debug, guesses, parinfo, save, annotate, show_components, use_lmfit, verbose, clear, reset_selection, fit_plotted_area, use_window_limits, vheight, exclude, **kwargs)
    345                               debug=debug, use_lmfit=use_lmfit,
    346                               fittype=fittype,
--> 347                               guesses=guesses, annotate=annotate, **kwargs)
    348             else:
    349                 raise ValueError("Guess and parinfo were somehow invalid.")

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in multifit(self, fittype, renormalize, annotate, show_components, verbose, color, guesses, parinfo, reset_fitspec, use_window_limits, use_lmfit, plot, **kwargs)
    810                           show_components=show_components,
    811                           use_window_limits=use_window_limits,
--> 812                           **kwargs)
    813
    814         # Re-organize modelerrs so that any parameters that are tied to others inherit the errors of the params they are tied to

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in plot_fit(self, xarr, annotate, show_components, composite_fit_color, lw, composite_lw, pars, offset, use_window_limits, show_hyperfine_components, plotkwargs, **kwargs)
   1155
   1156         if annotate or ((annotate is None) and self.autoannotate):
-> 1157             self.annotate()
   1158             if self.vheight: self.Spectrum.baseline.annotate()
   1159

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in annotate(self, loc, labelspacing, markerscale, borderpad, handlelength, handletextpad, fontsize, frameon, chi2, optimal_chi2_kwargs, **kwargs)
   1324         pl = matplotlib.collections.CircleCollection([0],edgecolors=['k'])
   1325         if hasattr(self.fitter,'annotations'):
-> 1326             self._annotation_labels = self.fitter.annotations()
   1327         else:
   1328             raise Exception("Fitter %s has no annotations." % self.fitter)

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/models/model.py in annotations(self, shortvarnames, debug)
    678             else:
    679                 label = ("$%s(%i)$=%8s $\\pm$ %8s" % (varname,varnumber,
--> 680                     Decimal("%g" % value).quantize( Decimal("%0.2g" % (min(np.abs([value,error])))) ),
    681                     Decimal("%g" % error).quantize(Decimal("%0.2g" % (error))),))
    682             label_list.append(label)

TypeError: bad operand type for abs(): 'NoneType'
```

**Comment by keflavich** [comment]
We don't yet understand the problem in SCOUSE, but it should be solved by this PR:
https://github.com/pyspeckit/pyspeckit/pull/290
in pyspeckit, at least to first order...

**Comment by jdhenshaw** [comment]
Could this be something to do with the accuracy of the input guesses? SCOUSE is failing on a type error, but pyspeckit is producing the 'None' value for the errors - i.e. I don't think SCOUSE is passing None values to pyspeckit causing it to crash

**Comment by GiantMolecularCloud** [comment]
My guesses weren't too bad for the spectra that crashed scouse. I used extremly bad guesses by accident and to test the algorithm but it always came up with a reasonable solution. So I don't think the user input is the problem. It could still be some internal calculations on the user input though.
It might be relevant that the crashes only occured on spectra that came after I accepted a proposed fit and it was never the spectrum after I used 'f' to manually re-fit the spectrum.

**Comment by jdhenshaw** [comment]
yes, so in this instance SCOUSE is using the best-fitting solution of the previous spectrum as an initial guess to the fitting of the new spectrum (the one that crashes). The initial guess that is fed to pyspeckit has a very high accuracy so I'm wondering if lmfit just gets hung up on a particular value @keflavich ?

**Comment by keflavich** [comment]
@jdhenshaw did you ever send me a test spectrum?  I need to reproduce the problem directly in order to debug it.  Maybe you did and I missed it.... in any case, let's try to work on this on a pyspeckit issue thread

**Comment by jdhenshaw** [comment]
yep I did - i'll ping you a reminder

**Comment by GiantMolecularCloud** [comment]
This commit does not fix the problem, unfortunately. A traceback is appended.

As a sidenote: Using colors in the printed output is nice as it lets the relevant information stand out more.

```
=====================================================
Fitting 7 out of 23
=====================================================
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-31834ddaffa6> in <module>
      1 s = scouse.stage_2(s,
      2                    verbose     = True,
----> 3                    write_ascii = True
      4                   )

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/scouse.py in stage_2(self, verbose, write_ascii, autosave, bitesize, nspec, training_set)
    469                     bf = fitting(self, SAA, saa_dict, SAAid,
    470                                  training_set=self.training_set,
--> 471                                  init_guess=firstfit)
    472                 SAAid = SAA.index
    473                 firstfit=False

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py in fitting(self, scouseobject, SAA, saa_dict, count, training_set, init_guess, guesses)
    296                                             count, guesses=guesses,
    297                                             training_set=True,
--> 298                                             init_guess=init_guess)
    299
    300         return bf

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py in fitting(self, scouseobject, SAA, saa_dict, count, training_set, init_guess, guesses)
    265             self.spec = spec
    266             self.trainingset_fit(spec, init_guess=init_guess,
--> 267                                        guesses=guesses)
    268
    269             with warnings.catch_warnings():

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py in trainingset_fit(self, spec, init_guess, guesses)
    206                          guesses=guesses,
    207                          fittype=scouseobject.fittype,
--> 208                          use_lmfit=True)
    209             spec.specfit.plot_fit(show_components=True)
    210             spec.specfit.plotresiduals(axis=spec.plotter.axis,

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/config.py in decorator(self, *args, **kwargs)
    143             new_kwargs[arg] = kwargs[arg]
    144
--> 145         f(self, *args, **new_kwargs)
    146
    147     # documentation should be passed on, else sphinx doesn't work and the user can't access the docs

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in __call__(self, interactive, usemoments, fittype, clear_all_connections, debug, guesses, parinfo, save, annotate, show_components, use_lmfit, verbose, clear, reset_selection, fit_plotted_area, use_window_limits, vheight, exclude, **kwargs)
    345                               debug=debug, use_lmfit=use_lmfit,
    346                               fittype=fittype,
--> 347                               guesses=guesses, annotate=annotate, **kwargs)
    348             else:
    349                 raise ValueError("Guess and parinfo were somehow invalid.")

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in multifit(self, fittype, renormalize, annotate, show_components, verbose, color, guesses, parinfo, reset_fitspec, use_window_limits, use_lmfit, plot, **kwargs)
    810                           show_components=show_components,
    811                           use_window_limits=use_window_limits,
--> 812                           **kwargs)
    813
    814         # Re-organize modelerrs so that any parameters that are tied to others inherit the errors of the params they are tied to

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in plot_fit(self, xarr, annotate, show_components, composite_fit_color, lw, composite_lw, pars, offset, use_window_limits, show_hyperfine_components, plotkwargs, **kwargs)
   1155
   1156         if annotate or ((annotate is None) and self.autoannotate):
-> 1157             self.annotate()
   1158             if self.vheight: self.Spectrum.baseline.annotate()
   1159

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in annotate(self, loc, labelspacing, markerscale, borderpad, handlelength, handletextpad, fontsize, frameon, chi2, optimal_chi2_kwargs, **kwargs)
   1324         pl = matplotlib.collections.CircleCollection([0],edgecolors=['k'])
   1325         if hasattr(self.fitter,'annotations'):
-> 1326             self._annotation_labels = self.fitter.annotations()
   1327         else:
   1328             raise Exception("Fitter %s has no annotations." % self.fitter)

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/models/model.py in annotations(self, shortvarnames, debug)
    678             else:
    679                 label = ("$%s(%i)$=%8s $\\pm$ %8s" % (varname,varnumber,
--> 680                     Decimal("%g" % value).quantize( Decimal("%0.2g" % (min(np.abs([value,error])))) ),
    681                     Decimal("%g" % error).quantize(Decimal("%0.2g" % (error))),))
    682             label_list.append(label)

TypeError: bad operand type for abs(): 'NoneType'
```

**Comment by GiantMolecularCloud** [comment]
The newest pyspeckit version 0.1.22.dev2847 and scousepy nones branch seem to fix this issue. At least, I didn't happen for ~60 stage2 fits while yesterday ~1 in 10-15 caused scousepy to crash.
However, there is new bug:

```
=====================================================
Fitting 16 out of 23
=====================================================

Legend.draggable() is drepecated in favor of Legend.set_draggable(). Legend.draggable may be reintroduced as a property in future releases.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/texmanager.py in _run_checked_subprocess(self, command, tex)
    297                                              cwd=self.texcache,
--> 298                                              stderr=subprocess.STDOUT)
    299         except subprocess.CalledProcessError as exc:

~/anaconda/envs/python3/lib/python3.6/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337

~/anaconda/envs/python3/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    417             raise CalledProcessError(retcode, process.args,
--> 418                                      output=stdout, stderr=stderr)
    419     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/Users/krieger/.matplotlib/tex.cache/c72ee30e927fd9040811fb01d35d7140.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-2-fa931801283c> in <module>
     20 s = scouse.stage_2(s,
     21                    verbose     = True,
---> 22                    write_ascii = True
     23                   )

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/scouse.py in stage_2(self, verbose, write_ascii, autosave, bitesize, nspec, training_set)
    469                     bf = fitting(self, SAA, saa_dict, SAAid,
    470                                  training_set=self.training_set,
--> 471                                  init_guess=firstfit)
    472                 SAAid = SAA.index
    473                 firstfit=False

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py in fitting(self, scouseobject, SAA, saa_dict, count, training_set, init_guess, guesses)
    296                                             count, guesses=guesses,
    297                                             training_set=True,
--> 298                                             init_guess=init_guess)
    299
    300         return bf

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py in fitting(self, scouseobject, SAA, saa_dict, count, training_set, init_guess, guesses)
    265             self.spec = spec
    266             self.trainingset_fit(spec, init_guess=init_guess,
--> 267                                        guesses=guesses)
    268
    269             with warnings.catch_warnings():

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py in trainingset_fit(self, spec, init_guess, guesses)
    206                          guesses=guesses,
    207                          fittype=scouseobject.fittype,
--> 208                          use_lmfit=True)
    209             spec.specfit.plot_fit(show_components=True)
    210             spec.specfit.plotresiduals(axis=spec.plotter.axis,

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/config.py in decorator(self, *args, **kwargs)
    143             new_kwargs[arg] = kwargs[arg]
    144
--> 145         f(self, *args, **new_kwargs)
    146
    147     # documentation should be passed on, else sphinx doesn't work and the user can't access the docs

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in __call__(self, interactive, usemoments, fittype, clear_all_connections, debug, guesses, parinfo, save, annotate, show_components, use_lmfit, verbose, clear, reset_selection, fit_plotted_area, use_window_limits, vheight, exclude, **kwargs)
    345                               debug=debug, use_lmfit=use_lmfit,
    346                               fittype=fittype,
--> 347                               guesses=guesses, annotate=annotate, **kwargs)
    348             else:
    349                 raise ValueError("Guess and parinfo were somehow invalid.")

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in multifit(self, fittype, renormalize, annotate, show_components, verbose, color, guesses, parinfo, reset_fitspec, use_window_limits, use_lmfit, plot, **kwargs)
    810                           show_components=show_components,
    811                           use_window_limits=use_window_limits,
--> 812                           **kwargs)
    813
    814         # Re-organize modelerrs so that any parameters that are tied to others inherit the errors of the params they are tied to

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in plot_fit(self, xarr, annotate, show_components, composite_fit_color, lw, composite_lw, pars, offset, use_window_limits, show_hyperfine_components, plotkwargs, **kwargs)
   1156
   1157         if annotate or ((annotate is None) and self.autoannotate):
-> 1158             self.annotate()
   1159             if self.vheight: self.Spectrum.baseline.annotate()
   1160

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py in annotate(self, loc, labelspacing, markerscale, borderpad, handlelength, handletextpad, fontsize, frameon, chi2, optimal_chi2_kwargs, **kwargs)
   1371             self.fitleg.draggable(True)
   1372             if self.Spectrum.plotter.autorefresh:
-> 1373                 self.Spectrum.plotter.refresh()
   1374
   1375     def print_fit(self, print_baseline=True, **kwargs):

~/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/plotters.py in refresh(self)
    547     def refresh(self):
    548         if self.axis is not None:
--> 549             self.axis.figure.canvas.draw()
    550
    551

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    400         toolbar = self.toolbar
    401         try:
--> 402             self.figure.draw(self.renderer)
    403             # A GUI class may be need to update a window using this draw, so
    404             # don't forget to call the superclass.

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/figure.py in draw(self, renderer)
   1647
   1648             mimage._draw_list_compositing_images(
-> 1649                 renderer, self, artists, self.suppressComposite)
   1650
   1651             renderer.close_group('figure')

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2626             renderer.stop_rasterizing()
   2627
-> 2628         mimage._draw_list_compositing_images(renderer, self, artists)
   2629
   2630         renderer.close_group('axes')

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/legend.py in draw(self, renderer)
    634         # update the location and size of the legend. This needs to
    635         # be done in any case to clip the figure right.
--> 636         bbox = self._legend_box.get_window_extent(renderer)
    637         self.legendPatch.set_bounds(bbox.x0, bbox.y0,
    638                                     bbox.width, bbox.height)

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_window_extent(self, renderer)
    248         get the bounding box in display space.
    249         '''
--> 250         w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
    251         px, py = self.get_offset(w, h, xd, yd, renderer)
    252         return mtransforms.Bbox.from_bounds(px - xd, py - yd, w, h)

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent_offsets(self, renderer)
    368
    369         whd_list = [c.get_extent(renderer)
--> 370                     for c in self.get_visible_children()]
    371         whd_list = [(w, h, xd, (h - yd)) for w, h, xd, yd in whd_list]
    372

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in <listcomp>(.0)
    368
    369         whd_list = [c.get_extent(renderer)
--> 370                     for c in self.get_visible_children()]
    371         whd_list = [(w, h, xd, (h - yd)) for w, h, xd, yd in whd_list]
    372

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent(self, renderer)
    241         Return with, height, xdescent, ydescent of box
    242         """
--> 243         w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
    244         return w, h, xd, yd
    245

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent_offsets(self, renderer)
    437
    438         whd_list = [c.get_extent(renderer)
--> 439                     for c in self.get_visible_children()]
    440
    441         if not whd_list:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in <listcomp>(.0)
    437
    438         whd_list = [c.get_extent(renderer)
--> 439                     for c in self.get_visible_children()]
    440
    441         if not whd_list:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent(self, renderer)
    241         Return with, height, xdescent, ydescent of box
    242         """
--> 243         w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
    244         return w, h, xd, yd
    245

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent_offsets(self, renderer)
    368
    369         whd_list = [c.get_extent(renderer)
--> 370                     for c in self.get_visible_children()]
    371         whd_list = [(w, h, xd, (h - yd)) for w, h, xd, yd in whd_list]
    372

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in <listcomp>(.0)
    368
    369         whd_list = [c.get_extent(renderer)
--> 370                     for c in self.get_visible_children()]
    371         whd_list = [(w, h, xd, (h - yd)) for w, h, xd, yd in whd_list]
    372

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent(self, renderer)
    241         Return with, height, xdescent, ydescent of box
    242         """
--> 243         w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
    244         return w, h, xd, yd
    245

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent_offsets(self, renderer)
    437
    438         whd_list = [c.get_extent(renderer)
--> 439                     for c in self.get_visible_children()]
    440
    441         if not whd_list:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in <listcomp>(.0)
    437
    438         whd_list = [c.get_extent(renderer)
--> 439                     for c in self.get_visible_children()]
    440
    441         if not whd_list:

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/offsetbox.py in get_extent(self, renderer)
    816             "lp", self._text._fontproperties, ismath=False)
    817
--> 818         bbox, info, d = self._text._get_layout(renderer)
    819         w, h = bbox.width, bbox.height
    820

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/text.py in _get_layout(self, renderer)
    311                 w, h, d = renderer.get_text_width_height_descent(clean_line,
    312                                                         self._fontproperties,
--> 313                                                         ismath=ismath)
    314             else:
    315                 w, h, d = 0, 0, 0

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in get_text_width_height_descent(self, s, prop, ismath)
    207             fontsize = prop.get_size_in_points()
    208             w, h, d = texmanager.get_text_width_height_descent(
--> 209                 s, fontsize, renderer=self)
    210             return w, h, d
    211

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/texmanager.py in get_text_width_height_descent(self, tex, fontsize, renderer)
    462         else:
    463             # use dviread. It sometimes returns a wrong descent.
--> 464             dvifile = self.make_dvi(tex, fontsize)
    465             with dviread.Dvi(dvifile, 72 * dpi_fraction) as dvi:
    466                 page = next(iter(dvi))

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/texmanager.py in make_dvi(self, tex, fontsize)
    326                 self._run_checked_subprocess(
    327                     ["latex", "-interaction=nonstopmode", "--halt-on-error",
--> 328                      texfile], tex)
    329             for fname in glob.glob(basefile + '*'):
    330                 if not fname.endswith(('dvi', 'tex')):

~/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/texmanager.py in _run_checked_subprocess(self, command, tex)
    305                     prog=command[0],
    306                     tex=tex.encode('unicode_escape'),
--> 307                     exc=exc.output.decode('utf-8')))
    308         _log.debug(report)
    309         return report

RuntimeError: latex was not able to process the following string:
b'\\\\Delta x(0)=None'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/Users/krieger/.matplotlib/tex.cache/c72ee30e927fd9040811fb01d35d7140.tex
LaTeX2e <2018-04-01> patch level 5
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2018/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/ts1enc.def
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/local/texlive/2018/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2018/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

)
No file c72ee30e927fd9040811fb01d35d7140.aux.
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Missing $ inserted.
<inserted text>
                $
l.14 ...ize{10.000000}{12.500000}{\rmfamily \Delta
                                                   x(0)=None}
No pages of output.
Transcript written on c72ee30e927fd9040811fb01d35d7140.log.





'enter' key acknowledged. Solution accepted.

Traceback (most recent call last):
  File "/Users/krieger/anaconda/envs/python3/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/Users/krieger/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/stage_2.py", line 71, in interactive_callback
    scouse=self.scouseobject)
  File "/Users/krieger/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/solution_description.py", line 47, in __init__
    fit_pars(self, spec, scouse)
  File "/Users/krieger/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev243-py3.6.egg/scousepy/solution_description.py", line 179, in fit_pars
    self._dof = spec.specfit.dof
  File "/Users/krieger/anaconda/envs/python3/lib/python3.6/site-packages/pyspeckit/spectrum/fitters.py", line 616, in dof
    raise AttributeError('No fit has been run, so npix_fitted is not '
AttributeError: No fit has been run, so npix_fitted is not defined and dof cannot be computed.
In [3]:
```

**Comment by jdhenshaw** [comment]
woah....this looks like a pyspeckit thing...I think @keflavich ??

**Comment by jdhenshaw** [comment]
how did you create this error message? Is this just for one of the spectra?

**Comment by GiantMolecularCloud** [comment]
Yes, it happened exactly the same way as before: when waiting for the next spectrum to show up this popped up without any obvious reason. This time it happened after a manual fit, so it's probably not related to the old bug.
The bug or the message threw me out of stage_2. The command line appeared again, the next spectrum showed anyway but I cannot advance to the next spectrum anymore and have to start over.
