### ISSUE TITLE
restarted from stage 5 error: type object 'fg' has no attribute '_endc_'

### ISSUE THREAD

**Issue by keflavich** [jdhenshaw/scousepy#43]
```
Beginning stage_6 analysis...

Traceback (most recent call last):
  File "/lustre/aginsbur/sgrb2/2013.1.00269.S/run_scouse_hc3n.py", line 95, in <module>
    s = scouse.stage_6(s, plot_neighbours=True, radius_pix = 2, figsize = [18,10], plot_residuals=True, write_ascii=True, verbose=verb)
  File "/lustre/aginsbur/repos/scousepy/scousepy/scouse.py", line 905, in stage_6
    "completed."+colors.fg._endc_)
AttributeError: type object 'fg' has no attribute '_endc_'

```

Haven't investigated, but we should do _something_ about this.

**Comment by jdhenshaw** [comment]
oops yep, that doesn't work.

**Comment by keflavich** [comment]
OK, that solved that error.  Now I see:
```
Beginning stage_6 analysis...

Traceback (most recent call last):
  File "/lustre/aginsbur/sgrb2/2013.1.00269.S/run_scouse_hc3n.py", line 95, in <module>
    s = scouse.stage_6(s, plot_neighbours=True, radius_pix = 2, figsize = [18,10], plot_residuals=True, write_ascii=True, verbose=verb)
  File "/lustre/aginsbur/repos/scousepy/scousepy/scouse.py", line 907, in stage_6
    "completed."+colors._endc_)
ValueError: No spectra are selected to be fit. Re-fitting individual spectra has completed.
```
which I guess means that I unintentionally skipped stage 5?  

This message looks fine; why is it a value error?

**Comment by jdhenshaw** [comment]
Hmmm I can't remember. But I do remember it serving a purpose once upon a time. Not sure it needs to be a value error though, you're right..

**Comment by keflavich** [comment]
Well, I guess that means my fits are done.  What should I do with the data now?  Do you have any good "plot everything summary" scripts around?

**Comment by keflavich** [comment]
on that note, I think we need to hook scouse up with the pyspeckit cube viewer

**Comment by keflavich** [comment]
see e.g. https://github.com/pyspeckit/pyspeckit/pull/306
