### ISSUE TITLE
Update tutorial data set - crashes on load

### ISSUE THREAD

**Issue by jdhenshaw** [jdhenshaw/scousepy#53]
Issue is the additional 4th axis in this fits file: https://github.com/jdhenshaw/scousepy_tutorials/blob/master/data/n2h%2B10_37.fits 

need to trim this 4th axis and re run if there is an error similar to the one below... 
 
```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/opt/anaconda3/lib/python3.8/site-packages/scousepy-1.0.1.dev92+gad6f30b-py3.8.egg/scousepy/scouse.py", line 335, in stage_1
  self.load_cube(fitsfile=fitsfile)
 File "/opt/anaconda3/lib/python3.8/site-packages/scousepy-1.0.1.dev92+gad6f30b-py3.8.egg/scousepy/scouse.py", line 925, in load_cube
  _cube = SpectralCube.read(fitsfile).with_spectral_unit(u.km/u.s,
 File "/opt/anaconda3/lib/python3.8/site-packages/spectral_cube/io/core.py", line 118, in __call__
  return registry.read(BaseSpectralCube, filename, *args, **kwargs)
 File "/opt/anaconda3/lib/python3.8/site-packages/astropy/io/registry.py", line 520, in read
  data = reader(*args, **kwargs)
 File "/opt/anaconda3/lib/python3.8/site-packages/spectral_cube/io/fits.py", line 204, in load_fits_cube
  wcs = WCS(header)
 File "/opt/anaconda3/lib/python3.8/site-packages/astropy/wcs/wcs.py", line 530, in __init__
  self.wcs.set()
astropy.wcs._wcs.SingularMatrixError: ERROR 3 in wcsset() at line 2507 of file cextern/wcslib/C/wcs.c:
Linear transformation matrix is singular.
ERROR 3 in linset() at line 636 of file cextern/wcslib/C/lin.c:
PCi_ja matrix is singular.
```

**Comment by keflavich** [comment]
There's nothing wrong with the file:
```python
>>> cube = SpectralCube.read('n2h+10_37.fits')
WARNING: FITS file has no STOKES axis, but it has a blank axis type at index 4 that is assumed to be stokes. [spectral_cube.cube_utils]
WARNING: Could not parse unit K(Tmb) [spectral_cube.cube_utils]
WARNING: StokesWarning: Cube is a Stokes cube, returning spectral cube for I component [spectral_cube.io.core]
```

**Comment by keflavich** [comment]
Which example caused this problem?

**Comment by jdhenshaw** [comment]
fix that worked described here: https://github.com/radio-astro-tools/spectral-cube/issues/445 

Though I'm at a loss to understand why this wouldn't have been a problem for me before now...I was totally unable to reproduce the error (found by someone else)

**Comment by jdhenshaw** [comment]
This was an issue with the data cube (additional axis). Closing.
