### ISSUE TITLE
maps are not subscriptable

### ISSUE THREAD

**Issue by keflavich** [jdhenshaw/scousepy#55]
I get the error:

```
]Traceback (most recent call last):
  File "<ipython-input-20-e12c0a20cd7b>", line 1, in <module>
    s = scouse.stage_1(config=config_file, interactive=True) # GUI based
  File "/blue/adamginsburg/adamginsburg/repos/scousepy/scousepy/scouse.py", line 377, in stage_1
    generate_SAAs(self, coverageobject)
  File "/blue/adamginsburg/adamginsburg/repos/scousepy/scousepy/stage_1.py", line 169, in generate_SAAs
    SAA=results[j]
TypeError: 'map' object is not subscriptable
```

in stage 1.  This most likely results from this part:
https://github.com/jdhenshaw/scousepy/blob/5eb202897f000c44043c89dbf24d8e73cb665a10/scousepy/stage_1.py#L155-L169

in which `parallel_map` is used.  Most likely, we need to do `list(parallel_map...)` or restructure the loop on line 168-169 to loop over the entries in the map rather than an index.

**Comment by jdhenshaw** [comment]
can you dig into this a bit more and tell me what is in `results` in order to produce this error, `results` should be a list

**Comment by keflavich** [comment]
`results` is not a list because `map` does not return a list (and neither does `parallel_map`) - it returns a map object that is not subscriptable.  Since you haven't encountered this yourself, it's almost certainly a version issue; I'm using python3.9 with presumably a recent version of parallel_map.  I'll submit the PR for this, though, as I'm pretty sure I solved the issue

**Comment by jdhenshaw** [comment]
in all instances where this occurs in the code (stage 1 and 3) `parallel_map` (https://github.com/jdhenshaw/scousepy/blob/master/scousepy/parallel_map.py) returns `<class 'numpy.ndarray'>` - I'm in python3.10 (just updated my whole distribution to dig into steve's error)

**Comment by jdhenshaw** [comment]
Just wanted to touch base on this again, because I was unsure as to whether anything needs to be implemented. See the following line: https://github.com/jdhenshaw/scousepy/blob/444e572df6dca3bafe87e5fd3e257f7d178ad638/scousepy/parallel_map.py#L99

Can you let me know if this is still an issue or if i can close?

**Comment by keflavich** [comment]
I think this is still an issue but I can't investigate again this week or next.
