### ISSUE TITLE
ValueError: Too few parameters input.  Need at least 6 for ammonia models

### ISSUE THREAD

**Issue by ChaoOu-GXU** [jdhenshaw/scousepy#76]
Hi
In stage 2, I select the ammonia model to fit the spectra, while in stage 3, this cannot provide the same length parameters to the fitter.
`Traceback (most recent call last):
  File "/home/dell/scousepy_model/test_scousepy/test.py", line 15, in <module>
    s = scouse.stage_3(config=config_file)
  File "/home/dell/.local/lib/python3.10/site-packages/scousepy-2.1.3.dev14+gd5a4b08-py3.10.egg/scousepy/scouse.py", line 779, in stage_3
    indivspec_list_completed=autonomous_decomposition(self, indivspec_list)
  File "/home/dell/.local/lib/python3.10/site-packages/scousepy-2.1.3.dev14+gd5a4b08-py3.10.egg/scousepy/stage_3.py", line 141, in autonomous_decomposition
    results = parallel_map(decomposition_method, inputlist, numcores=scouseobject.njobs)
  File "/home/dell/.local/lib/python3.10/site-packages/scousepy-2.1.3.dev14+gd5a4b08-py3.10.egg/scousepy/parallel_map.py", line 167, in parallel_map
    return run_tasks(procs, err_q, out_q, numcores)
  File "/home/dell/.local/lib/python3.10/site-packages/scousepy-2.1.3.dev14+gd5a4b08-py3.10.egg/scousepy/parallel_map.py", line 94, in run_tasks
    raise err_q.get()
ValueError: Too few parameters input.  Need at least 6 for ammonia models

I don't know how to solve it. I hope I can get your help. 
Thank you

**Comment by jdhenshaw** [comment]
Hyperfine structure fitting is not yet implemented in ScousePy, it is in the pipeline but there will need to be significant development to get it up and running

**Comment by ChaoOu-GXU** [comment]
I get it. Thank you for your attention.
